# Site settings
name: <a href="/niming-resume/" target="_blank">力争上游，养家糊口</a>
email: zhouniyao@163.com
author: Ni Ming
url: https://bihusenlan.github.io
resume_site: https://bihusenlan.github.io
github: https://github.com/bihusenlan
baseurl: ""  #根目录
description: 我只佩服两类人：一种是改变世界的人，另一种是教会别人改变世界的人。
motto: 倪 明
#motto: 爱生活，写代码
banner: <marquee scrollamount="10" ><a href="/niming-resume/" target="_blank">倪明，毕业于云南师范大学，获 <b>计算机应用技术 硕士</b>学位。主要研究方向为计算机图形学、OpenGL ES、虚拟现实、Android游戏。目前使用平台<b> Unity3D</b>，语言 <b>C#</b>.</a></marquee>
#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
excerpt_separator:  '<!-- more -->' #文章摘要
paginate: 28
paginate_path: "page:num"
gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
github_username: niming
highlighter: rouge
markdown: kramdown
FB:
  comments :
    provider : disqus
    disqus :
        short_name : niming
 
