# Site settings
name: 倪 明
email: zhouniyao@163.com
author: NM
url: https://bihusenlan.github.io
resume_site: https://bihusenlan.github.io
github: https://github.com/bihusenlan
baseurl: ""  #根目录
description: <p align="Center">云南师范大学 计算机应用技术<b> 学硕</b></p><p align="Center"> 研究方向：计算机图形学</p><p align="Center">主攻<b> VR/Unity3D</b></p><p align="Center">数学基础好、学习能力强、算法功底扎实</p>
motto: 倪 明
#motto: 爱生活，写代码
banner: <a href="https://github.com/bihusenlan" target="_blank">倪明，毕业于云南师范大学，获 <b>计算机应用技术 硕士</b>学位。<br/>主要研究方向为计算机图形学、OpenGL ES、虚拟现实、Android游戏。目前使用平台<b> Unity3D</b>，语言 <b>C#</b>.</a>
#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
excerpt_separator:  '<!-- more -->' #文章摘要
paginate: 8
paginate_path: "page:num"
gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
github_username: maoxiaoke
highlighter: rouge
markdown: kramdown
FB:
  comments :
    provider : disqus
    disqus :
        short_name : xiaokedada
