# Site settings
name: 倪 明
email: zhouniyao@163.com
author: NM
url: https://bihusenlan.github.io
resume_site: https://bihusenlan.github.io
github: https://github.com/bihusenlan
baseurl: ""  #根目录
description: 云南师范大学计算机应用技术<b> 学硕</b></p><p align="Center"> 研究方向：计算机图形学</p><p align="Center">主攻<b> VR/Unity3D</b></p><p align="Center">数学基础好、学习能力强、算法功底扎实</p>
motto: 代码是游戏的灵魂
#motto: 爱生活，写代码
banner: 想找份Unity3D游戏开发工作
#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
excerpt_separator:  '<!-- more -->' #文章摘要
paginate: 8
paginate_path: "page:num"
gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
github_username: maoxiaoke
highlighter: rouge
markdown: kramdown
FB:
  comments :
    provider : disqus
    disqus :
        short_name : xiaokedada
