# Site settings
name: <a href="/niming-resume/" target="_blank">力争上游，养家糊口</a>
email: zhouniyao@163.com
author: Ni Ming
url: https://bihusenlan.github.io
resume_site: https://bihusenlan.github.io
github: https://github.com/bihusenlan
baseurl: ""  #根目录
description: 我只佩服两类人：一种是改变世界的人，另一种是教会别人改变世界的人。
motto: 倪 明
#motto: 爱生活，写代码
banner: <marquee scrollamount="10" ><a href="/niming-resume/" target="_blank">倪明，云南师范大学计算机应用技术 硕士研究生。 主要研究方向为计算机图形学、DirectX、OpenGL ES，非常熟悉 Unity3D / Unreal Engine4引擎，能灵活运用 C#、C++编程。会写Unity平台下的Shader Lab程序，会使用opencv对视频图像进行处理。</a></marquee>
#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
excerpt_separator:  '<!-- more -->' #文章摘要
paginate: 8
paginate_path: "page:num"
gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
github_username: niming
highlighter: rouge
markdown: kramdown
FB:
  comments :
    provider : disqus
    disqus :
        short_name : niming 
